### ISSUE TITLE
markdown-unlit unable to process file contaned unicode symbols

### ISSUE THREAD

**Issue by avnik** [sol/markdown-unlit#8]
```
log-warper-1.7.5: build (lib + exe + test)
Preprocessing library log-warper-1.7.5...
Preprocessing executable 'how-to' for log-warper-1.7.5...
markdown-unlit: examples/HowTo.lhs: hGetContents: invalid argument (invalid byte sequence)
`markdown-unlit' failed in phase `Literate pre-processor'. (Exit code: 1
```

so it should be specified, what encoding to use:
`hSetEncoding inputHandle utf8`

Full example here: https://stackoverflow.com/questions/33444796/read-file-with-utf-8-in-haskell-as-io-string

**Comment by kirelagin** [comment]
Allow me to provide some additional details.

The problem is that `markdown-unlit` uses `readFile` to get the contents of the file to process. `readFile` is pretty dumb and it will trip on non-ascii characters if the locale of the system does not use UTF-8. This is a known “not a but but feature” related to console output.

Anyway, Haskell source files are always UTF-8 encoded, regardless of the OS used and of the locale chosen, so the right thing to do is to always use UTF-8 when processing them (see e.g. [GHC Trac #10762](https://ghc.haskell.org/trac/ghc/ticket/10762) for an example of a similar issue).

To reproduce the issue:

1. Create a file called `test.md` with the following text:
    ```
    Привет!
    ````
2. Run `LC_ALL=C markdown-unlit -t test test.md test.md.unlit`.

The result is:

```
markdown-unlit: test.md: hGetContents: invalid argument (invalid byte sequence)
```
